services:
  - type: web
    name: movia-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3
      - key: CLIENT_URL
        sync: false
